const cards_es = [
    { place: 'Cristo Redentor', state: 'Rio de Janeiro', img: './images/cristo_redentor.jpg', right_text: 'Lo has hecho bien. Pero hay hay alguién que no sepa dónde está? El Cristo Redentor es una enorme estatua de Jesús con los brazos abiertos mostrando a la ciudad de Río de Janeiro. La estatua tiene una altura de 30,1 metros sobre un pedestal de 8 metros. Inaugurado en 1931, es considerado el monumento Art decó más grande del mundo!' },
    { place: 'Jalapão', state: 'Tocantins', img: './images/jalapao.jpg', right_text: '¡Ole, tú! En Tocatins se encuentra el Parque Jalapão, una región árida salpicada de oasis. Tiene una temperatura media de 30 grados centígrados y su área total es de 34.000 kilómetros cuadrados. Está cortado por una inmensa red de ríos y riachuelos, todos de agua clara y transparente. ' },
    { place: 'Encontros das Aguas', state: 'Amazonas', img: './images/encontro_aguas.jpg', right_text: '¡Muy bien! El encuentro de las aguas es la confluencia del río Negro, de aguas más oscuras casi de color negro, con el río Solimões, de aguas más claras con tonalidad arcillosa. A partir de este tramo, el río recibe el nombre de Amazonas. Ahora, flipa:  durante 6 km las aguas de los dos ríos corren lado a lado sin mezclarse. Si tienes suerte, un delfín del amazonas, el “boto rosa” te acompañará durante el paseo.' },
    { place: 'Catedral Metropolitana', state: 'Distrito Federal', img: './images/catedral.jpg', right_text: '¡Eso es! Diseñada por el arquitecto Oscar Niemeyer, la Catedral Metropolitana está en Brasília. La mayor parte de la catedral está bajo tierra, con sólo el techo ovalado del baptisterio y el campanario visible por encima del suelo. Y escucha eso: las campanas de la iglesia han sido fabricadas en Miranda de Ebro y donadas a Brasil por el Gobierno de España.' },
    { place: 'Lençóis Maranhenses', state: 'Maranhão', img: './images/lencois.jpg', right_text: '¡Lo has clavado! A vista de pájaro, las dunas parecen sábanas blancas tendidas al viento. De hecho, el nombre de este lugar, Lençóis Maranhenses, significa «sábanas de Maranhão», el estado de la costa del nordeste de Brasil donde se encuentran las dunas con forma de media luna. Al margen del topónimo, es un desierto mágico, con ola tras ola de arena blanca y resplandeciente. Llegar allá no es fácil pero vale la pena.' },
    { place: 'Frevo', state: 'Pernambuco', img: './images/frevo.jpg', right_text: '¡Bien! El frevo es una expresión artística musical y bailada que se practica principalmente durante el carnaval de Recife. El ritmo rápido, frenético y potente de su música se basa en la fusión de géneros como la marcha, el tango brasileño, la contradanza, la polka y piezas de música clásica. Pero ojo: "frevo" viene de frever, corruptela del portugués ferver (hervir). Seguir el ritmo te garantizo que no será muy fácil... Pero vamos... Tu mismo.' },
    { place: 'Monte Roraima', state: 'Roraima', img: './images/roraima.jpg', right_text: '¡Así es! Monte Roraima, también conocido como Tepuy Roraima o Cerro Roraima, es una montaña de 2.810 metros de altura localizada en la sierra sudamericana de Pacaraima, en la frontera entre Venezuela, Brasil y Guyana. La cima es una meseta de 31km² rodeada por unos acantilados de 400 metros de altura, lo que le da un aspecto realmente espectacular.' },
    { place: 'Acarajé', state: 'Bahia', img: './images/acaraje.jpg', right_text: '¡Punto! Símbolo de la gastronomía bahiana, el acarajé está hecho con alubias cocidas y hechos puré, moldeado con forma de bollo y fritos en aceite de dendê. Se sirve relleno con vatapá y caruru, pastas picantes hechas de gambas e anacardos molidos. Y lo más curioso: en Salvador, solamente está permitido vender acarajé hecho con la receta original y también es obligatório llevar el traje tradicional de bahiana.' },
    { place: 'Boi-Bumbá de Parintins', state: 'Amazonas', img: './images/bumba.jpg', right_text: '¡Lo has acertado! El Festival Folclórico de Parintins es una fiesta realizada anualmente en el último fin de semana de junio en Parintins. El festival es una representación a cielo abierto, donde compiten dos asociaciones: Boi Garantido, de color rojo, y el Boi Caprichoso, de color azul. La representación ocurre en el Bumbódromo, un tipo de estadio con la forma de una cabeza de buey estilizada, con capacidad para 35 mil espectadores.' },
    { place: 'Cataratas do Iguaçu', state: 'Paraná', img: './images/foz.jpg', right_text: '¡Muy bien! Las cataratas del Iguazú son reconocidas de forma unánime como las más espectaculares del mundo. El botánico suizo Robert Chodat describió elocuentemente su imponente grandeza: “Cuando nos encontramos al pie de este mundo de cascadas, y alzando los ojos vemos, a 82 metros por encima de nosotros, el horizonte ocupado por una línea de aguas, el asombroso espectáculo de un océano cayendo a raudales en un abismo es casi escalofriante.”' },
    { place: 'San Juan de Campina Grande', state: 'Paraíba', img: './images/festa_junina.jpg', right_text: '¡Punto! El mayor San Juan del mundo, es un evento anual celebrado en Campina Grande, en el estado brasileño de Paraíba, durante el mes de junio. En la cultura del nordeste brasileño, es típico celebrar el día de São João a través de espectáculos, bailes y bandas. La fiesta dura 31 días y se celebra en el Parque do Povo, "el cuartel general del forró", en el centro de la ciudad.' },
    // { place: 'Pantanal', state: 'Mato Grosso', img: './images/pantanal.jpg', right_text: '¡Bien! El Parque Nacional del Pantanal Matogrossense está situado en el suroeste de Mato Grosso y tiene 136.028,00 hectáreas. En el parque viven increíbles animales como el jaguar, el oso hormiguero gigante, caimanes y la guacamaya azul.' },
    { place: 'Alter do Chão', state: 'Pará', img: './images/alter.jpg', right_text: '¡Olé! Esta pequeña aldea de pescadores, en el amazónico estado de Pará, compite en exotismo y belleza con los más renombrados balnearios oceánicos del mundo. Estas playas, bañadas por las cristalinas y tibias aguas del río Tapajós, alcanzan su mayor esplendor en el segundo semestre del año cuando la sequía permite que islas de arena blanca emerjan imponentes rodeadas de aguas que cambian sus tonalidades de azul de acuerdo con la luminosidad del día.' },
    { place: 'Represa de Furnas', state: 'Minas Gerais', img: './images/capitolio.jpg', right_text: 'Nada mal... El Lago de Furnas es un proyecto de 1963 para la creación de la Central Hidroeléctrica de Furnas y abarca 34 municipios. Es uno de los lagos artificiales más grandes del mundo, con 1.406,26 Km². Es considerado el "Mar de Minas" con aguas que van del azul turquesa al verde esmeralda. Su construcción ha impulsado el turismo en la región, debido a los hermosos paisajes formados por los cañones y cascadas, además de la práctica de deportes náuticos.' },
    { place: 'Chapada dos Veadeiros', state: 'Goiás', img: './images/veadeiros.jpg', right_text: '¡Lo has heco muy bien! La Chapada dos Veadeiros es un parque nacional situado en el estado de Goiás, en la cima de una antigua meseta con una edad estimada de 1.800 millones de años. La región se desarrolló primero alrededor de la fiebre de las minas de oro en el siglo XVIII. Cavalcante fue uno de los primeros pueblos fundados en la región, y en un momento dado se convirtió en uno de los mayores extractores de oro de Brasil.' },
    { place: 'Oktoberfest', state: 'Santa Catarina', img: './images/blumenau.jpg', right_text: '¿Estás flipando, ¿no? Pero lo has hecho bien. La Oktoberfest de Blumenau fue creada en 1984. Desde su primera edición ha sido un éxito, y hoy en día cuenta con una asistencia de alrededor de 700.000 personas al año. El evento presenta bailes folclóricos (Tanzgruppen), partidos de tiro (Schützenvereine), canciones alemanas, trajes folclóricos y cocina alemana.' },
    { place: 'Moqueca Capixaba', state: 'Espírito Santo', img: './images/moqueca.jpg', right_text: '¡Punto! La moqueca capixaba es un estofado de pescado y marisco que se elabora siempre en una panela de barro de color negro tintada con cáscara de manglar rojo y hecha a mano por las paneleiras de Vitória, la capital de Espírito Santo. Poca broma con estas cazuelas porque están catalogadas como bien patrimonial del país. Y cuidado con el plato, porque en dicho estado cuenta con su propia cofradía y su día nacional.' },
    { place: 'Chapada Diamantina', state: 'Bahia', img: './images/chapada_diamantina.jpg', right_text: '¡Has marcado punto! El Parque Chapada Diamantina es conocido por sus curiosas formaciones de roca, su serranía, cañones, cascadas y valles. Pero bajo tierra, también hay numerosas sorpresas. Algunos pozos naturales, están inundados con aguas tan cristalinas, que permiten ver hacia la profundidad con total facilidad. El Pozo Azul tiene la particularidad de que, al nadar en sus aguas transparentes, da la sensación de estar levitando.' },
    { place: 'Fernando de Noronha', state: 'Pernambuco', img: './images/noronha.jpg', right_text: '¡Muy bien! Fernando de Noronha es un archipiélago de origen volcánico en el estado de Pernanbuco, cercano a su capital, Recife. Es uno de los mejores puntos de buceo de Brasil. Su infraestructura turística es muy básica (posadas familiares sin agua caliente), pocos restaurantes y, lo mejor, normas muy estrictas de preservación del lugar.' },
    { place: 'Bonito', state: 'Mato Grosso do Sul', img: './images/bonito.jpg', right_text: '¡Fenomenal! Ríos con aguas de vertiente, atravesando un lecho calcáreo en un clima cálido, aguas hiper cristalinas, y peces de colores,  no es una fórmula que abunde en la naturaleza. Bonito es una localidad alejada de las famosas imágenes de playa o de selva en el Amazonas. En éste rincón cercano al pantanal, lo que abunda es belleza natural en forma de cascadas o grutas, siempre con aguas cristalinas.' },
    { place: 'Maragogi', state: 'Alagoas', img: './images/maragogi.jpg', right_text: '¡Bien! Una pequeña ciudad de algo más de 26.000 habitantes que deslumbra por sus playas de agua turquesa cristalina, sus piscinas naturales, arrecifes de coral, y cocoteros además de su agradable clima (verano todo el año) y rica gastronomía.' },
    { place: 'Ouro Preto', state: 'Minas Gerais', img: './images/ouro_preto.jpg', right_text: '¡Fantástico! Esta antigua ciudad minera del oro te permitirá ver cómo era el país hace algunos siglos. Calles estrechas y empinadas perfectas para explorarlas a pie. Hay 23 iglesias preciosas en este pueblo, pero ninguna más hermosa que la Igreja de Nossa Senhora do Pilar con sus 900 kilos de oro y plata decorando el interior.' },
    { place: 'Arraial do Cabo', state: 'Rio de Janeiro', img: './images/arr_cabo.jpg', right_text: '¡Bien! En el estado de Río de Janeiro, está Arraial do Cabo. El paisaje costero, además de su belleza que salta a la vista, posee curiosidades, como ser el punto donde crecen las orquídeas más exóticas del mundo.' },
    { place: 'Catedral da Sé', state: 'São Paulo', img: './images/se.jpg', right_text: '¡Muy bien! La Catedral da Sé no pasa desapercibida entre los rascacielos de São Paulo. Es de estilo neogótico y de destaca por ser la iglesia más grande de São Paulo, con 111 metros de largo, 46 de ancho, dos torres de 92 metros de altura y una cúpula magistral. La iglesia tiene capacidad para 8.000 personas. ¡Flipa!' },
    { place: 'Ronaldinho Gaúcho', state: 'Rio Grande do Sul', img: './images/ronaldo.jpg', right_text: '¡Tampoco era tan complicado, ¡eh! Ronaldinho Gaúcho, claro, es gaúcho. Mundialmente reconocido como uno de los talentos más grandes en la historia del fútbol, Ronaldinho nació en Porto Alegre, capital del Rio Grande do Sul. Debutó como futbolista profesional en el club Grêmio de Porto Alegre, pero desarrolló gran parte de su carrera futbolista en Europa.' },
    { place: 'Jericoacoara', state: 'Ceará', img: './images/jericoacoara.jpg', right_text: '¡Correcto! Jericoacoara se ubica en el extremo oeste de la costa del estado de Ceará, a 300km de la capital, Fortaleza. La famosa playa de Jericoacoara es reconocida internacionalmente como una de las más bellas playas del mundo. Jericoacoara preserva lagunas cristalinas de agua dulce, playas de arena y médanos blancos, que se extienden por kilómetros y completan la fórmula que hace del lugar un verdadero pedazo del paraíso.' },
    { place: 'D.O.M Restaurante', state: 'São Paulo', img: './images/atala.jpg', right_text: 'Desde hace algunos años la gastronomía brasileña y sus chefs están adquiriendo un importante reconocimiento a nivel mundial. Uno de los mayores impulsores de esta nueva fama mundial es sin lugar a dudas el restaurante D.O.M que se destaca sobre todo por 2 rasgos que lo hacen diferente: un chef atípico y la utilización de productos exclusivamente locales, ¡incluyendo hormigas!.' },

];

const cards_en = [
    { place: 'Cristo Redentor', state: 'Rio de Janeiro', img: './images/cristo_redentor.jpg', right_text: 'You have done well! The Cristo Redentor is a huge statue of Jesus of Nazareth with his arms open in front of the city of Rio de Janeiro. It is nothing less than 30.1 meters on a pedestal of 8 meters. The Cristo was inaugurated in 1931, is considered the largest Art Deco monument in the world.' },
    { place: 'Jalapão', state: 'Tocantins', img: './images/jalapao.jpg', right_text: 'Good work! In Tocatins is the Jalapão Park, an arid region dotted with oases. It has an average temperature of 30 degrees Celsius and its total area is 34,000 square kilometers. It is crossed by an immense network of rivers, all with transparent water. The population density is 0.8 inhabitants per square kilometre.' },
    { place: 'Meeting of Waters', state: 'Amazonas', img: './images/encontro_aguas.jpg', right_text: 'The Encontro das águas - meeting of the waters - is the confluence of the Negro River, with dark and almost black waters, with the Solimões River, with lighter, clay-colored waters. From this stretch on, the river is called Amazon. Now, freak out: for 6 km, the waters of the two rivers run side by side without mixing.' },
    { place: 'Metropolitan Cathedral', state: 'Distrito Federal', img: './images/catedral.jpg', right_text: 'Designed by Oscar Niemeyer, the Metropolitan Cathedral Nossa Senhora Aparecida is the cathedral of Brasilia. Most of the cathedral is underground, with only the 70-metre ceiling, the oval roof of the baptistery and the bell tower visible above the ground.' },
    { place: 'Lençóis Maranhenses', state: 'Maranhão', img: './images/lencois.jpg', right_text: 'From a bird\'s eye view, the dunes look like white sheets stretched out in the evening wind. In fact, the name of this place, Lençóis Maranhenses, means "sheets of Maranhão", the state on the northeast coast of Brazil where the crescent-shaped dunes are located.' },
    { place: 'Frevo', state: 'Pernambuco', img: './images/frevo.jpg', right_text: 'Frevo is a music and danced artistic expression that is mainly practiced during Recife\'s carnival. The fast, frenetic and powerful rhythm of its music, performed by military bands, is based on the fusion of genres such as "marcha", polka and classical music pieces. It\'s a very funny dance, but following the rhythm will not be that easy... Good luck!' },
    { place: 'Mount Roraima', state: 'Roraima', img: './images/roraima.jpg', right_text: 'Mount Roraima, also known as Tepuy Roraima or Cerro Roraima, is a 2,810-meter high mountain located in the South American mountain range of Pacaraima, on the border between Venezuela, Brazil and Guyana. The peak is a 31km² plateau surrounded by 400m high cliffs, which gives it a truly spectacular appearance.' },
    { place: 'Acarajé', state: 'Bahia', img: './images/acaraje.jpg', right_text: 'A symbol of the Bahia\'s gastronomy, the acarajé is made from cooked and mashed "fradinho" beans, seasoned with salt and chopped onion, shaped like a bun and fried in dendê oil. It is served divided by half and filled with "vatapá" and caruru, spicy pastas made from prawns and ground cashew nuts.' },
    { place: 'Boi-Bumbá of Parintins', state: 'Amazonas', img: './images/bumba.jpg', right_text: 'The Parintins Folklore Festival is a popular festival held annually on the last weekend of June. The festival is an open-air performance, where two associations compete: Boi Garantido, in red, and Boi Caprichoso, in blue. The performance takes place at the Bumbódromo, a type of stadium in the shape of a stylized ox head.' },
    { place: 'Iguaçu Falls', state: 'Paraná', img: './images/foz.jpg', right_text: 'The Iguazu Falls are recognized as the most spectacular in the world. The botanist Robert Chodat described its: "When we stand at the foot of this world of waterfalls, and lifting our eyes up we see, 82 meters above us, the horizon occupied by a line of waters, the amazing spectacle of an ocean pouring into an abyss is almost terrifying".' },
    { place: 'Campina Grande Saint John\'s', state: 'Paraíba', img: './images/festa_junina.jpg', right_text: 'The largest Saint John\'s party in the world is an annual event held in Campina Grande, during the month of June. In the culture of northeastern Brazil, it\'s typical to celebrate São João\'s day through shows, dances and music. The festival lasts 31 days and is held in the "Parque do Povo", "the headquarters of the forró".' },
    // { place: 'Pantanal', state: 'Mato Grosso', img: './images/pantanal.jpg', right_text: 'The Pantanal Matogrossense National Park is a park located in Mato Grosso. With 136,028.00 hectares, it aims to protect and preserve the entire Pantanal ecosystem. In the park there are wonderful animals like the jaguar, the giant anteater, alligators and the blue macaw.' },
    { place: 'Alter do Chão', state: 'Pará', img: './images/alter.jpg', right_text: 'This small village competes in exoticism and beauty with the most renowned oceanic resorts in the world. These beaches, bathed by the crystalline and warm waters of the Tapajós River, reach their greatest splendor in the second half of the year when the drought allows white-sand islands to emerge surrounded by blue waters.' },
    { place: 'Lake of Furnas', state: 'Minas Gerais', img: './images/capitolio.jpg', right_text: 'The Lake of Furnas is a 1963 project for the creation of the Furnas Hydroelectric Power Station. It is one of the largest artificial lakes in the world, with 1,406.26 km². It is considered the "Sea of Minas Gerais" with waters that range from turquoise blue to emerald green.' },
    { place: 'Oktoberfest', state: 'Santa Catarina', img: './images/blumenau.jpg', right_text: 'The Oktoberfest of Blumenau was created in 1984, after a big flood of the Itajaí-Açu river, with the objective of recuperating the city\'s economy and raising the morale of its inhabitants. Since its first edition it has been a success, and today it has an attendance of about than 700,000/year!' },
    { place: 'Chapada dos Veadeiros', state: 'Goiás', img: './images/veadeiros.jpg', right_text: 'The Chapada dos Veadeiros is a national park, on the top of an ancient plateau. The region was first developed around the golden mine rush in the 18th Century. Cavalcante was one of the first villages founded in the region, and at one point became one of Brazil\'s major gold extractors.' },
    { place: 'Moqueca Capixaba', state: 'Espírito Santo', img: './images/moqueca.jpg', right_text: 'The moqueca capixaba is a fish and seafood dish that prepared in a black clay pot dyed with red mangrove shells and handmade from Vitória, the capital of Espírito Santo. They are classified as a national heritage product.' },
    { place: 'Chapada Diamantina', state: 'Bahia', img: './images/chapada_diamantina.jpg', right_text: 'The Chapada Diamantina Park is known for its curious rock formations, mountains, canyons, waterfalls and valleys. But, underground, there are also numerous surprises. Some natural wells, are flooded with water so crystalline, that allow to see towards the depth.' },
    { place: 'Fernando de Noronha', state: 'Pernambuco', img: './images/noronha.jpg', right_text: 'Fernando de Noronha is an archipelago of volcanic origin in the state of Pernanbuco, near its capital, Recife. It is one of the best diving spots in Brazil. Its tourist infrastructure is very basic (family inns without hot water), few restaurants and, best of all, very strict rules for the preservation of the place.' },
    { place: 'Bonito', state: 'Mato Grosso do Sul', img: './images/bonito.jpg', right_text: 'Rivers with waters of slope, crossing a calcareous riverbed in a warm climate, crystalline waters, and colorful fish, it is not a formula that abounds in nature. Bonito is near the Pantanal, what abounds is natural beauty in the form of waterfalls or caves.' },
    { place: 'Maragogi', state: 'Alagoas', img: './images/maragogi.jpg', right_text: 'A small city of just over 26,000 inhabitants that impresses with its beaches of crystalline turquoise water, natural pools, coral reefs, and coconut palms in addition to its pleasant weather (summer all year round) and rich gastronomy.' },
    { place: 'Ouro Preto', state: 'Minas Gerais', img: './images/ouro_preto.jpg', right_text: 'This ancient gold mining town will allow you to see how the country was some centuries ago. Narrow, hilly streets perfect for exploring on foot. There are 23 beautiful churches in this village, but none more beautiful than the Igreja de Nossa Senhora do Pilar with its 900 kilos of gold and silver decorating the interior.' },
    { place: 'Arraial do Cabo', state: 'Rio de Janeiro', img: './images/arr_cabo.jpg', right_text: 'In the state of Rio de Janeiro, there is Arraial do Cabo. The coastal landscape, besides its beauty that jumps to the eye, has curiosities, such as being the point where the most exotic orchids in the world grow.' },
    { place: 'Catedral da Sé', state: 'São Paulo', img: './images/se.jpg', right_text: 'All right! The Sé Cathedral does not go unnoticed between the skyscrapers of São Paulo. It is of neo-Gothic style and stands out as the largest church in São Paulo, with 111 meters long, 46 meters wide, two towers of 92 meters high and a magnificent dome. The church has a capacity of 8,000 souls!' },
    { place: 'Ronaldinho Gaúcho', state: 'Rio Grande do Sul', img: './images/ronaldo.jpg', right_text: 'It wasn\'t that complicated either, hey! Ronaldinho Gaúcho, of course, is "gaúcho". The world-renowned is one of the greatest talents in the history of football. He made his debut as a professional footballer at the Gremio Football Club, but spent much of his football career in Europe.' },
    { place: 'Jericoacoara', state: 'Ceará', img: './images/jericoacoara.jpg', right_text: 'Right! Jericoacoara is located in the state of Ceará. The famous Jericoacoara beach is internationally recognized as one of the most beautiful beaches in the world. Jericoacoara preserves crystalline fresh water lagoons, sandy beaches and white dunes.' },
    { place: 'D.O.M Restaurante', state: 'São Paulo', img: './images/atala.jpg', right_text: 'For some years now, Brazilian gastronomy and its chefs have been achieving huge renown around the world. One of the main promoters of this new world fame is undoubtedly the D.O.M. restaurant, which stands out above all for 2 features that make it different: an atypical chef and the use of exclusively local products, including ants!' },

];

const wrongAns_es = ['¿En sério?', '¡Te has pasado tres pueblos, chaval!', '¡Ni de coña!', 'A ver si viajamos un poco más, ¿no?', 'Te perderías en Brasil seguro!', '¡No, no y no!', 'Estás muy lejos del sítio correcto...', 'Madre mía, ¿por dónde vas?', 'Buffff... Un poco perdido sí que estás, ¿eh?', 'No tienes planes de ir a Brasil, espero...', '¿¿Estás de coña??']

const wrongAns_en = ['Seriously?', 'No way!', 'You\'d get lost in Brazil for sure!', 'No, no and NO!', 'You\'re a million miles away from the right place...', 'My God, where are you going?', 'Buffff... You\' re a little lost, aren\'t you?', 'You don\'t have any plans to go to Brazil, I hope...', 'Are you kidding me?', 'Please! I can\'t believe you choose this option!', 'WTF! Really? Give me a break!']

const START_BUTTON = ['¡Jugar!', 'Play!'];

const TRY_AGAIN = ['¡Otra vez!', 'Try Again!'];

const ZERO_POINTS = ['¡No has acertado ninguna!<br> No quiero ser borde... <br>Pero... ¿En qué mundo vives? <br>Seguro que eres de eses que ubica Buenos Aires como capital de Brasil. <br>Venga, prueba otra vez...', 'You didn\'t get one right! <br>I don\'t want to be rude... <br>But... Which world do you live in? <br>I\'m sure you\'re one of those who think of Buenos Aires as the capital of Brazil. <br>Come on, try again...']

const VERY_LOW_POINTS_ONE = ['Qué vergüenza... <br>¡Has conseguido solo ', 'If I were you, you\'d be a little ashamed... <br>You only got '];

const VERY_LOW_POINTS_TWO = [' puntos! <br>Brasil es el quinto país mas grande del mundo y ¿eso es todo que sabe de él?', ' points! <br>Brazil is the fifth largest country in the world and that\'s all you know about it?'];

const MIDDLE_POINTS_ONE = ['Has conseguido ', 'You have scored '];

const MIDDLE_POINTS_TWO = [' puntos. <br>No está mal para un gringo, pero tampoco es para tirar cohetes. <br>Espero que en la próxima lo hagas mejor.', ' points. <br>Not bad for a gringo, but nothing to celebrate either.<br> I hope you do better next time.'];

const HIGH_POINTS_ONE = ['¡Bueno, bueno! Has conseguido ', '¡You have scored '];

const HIGH_POINTS_TWO = [' puntos!<br>¡Estoy flipando, chaval! <br>Quién se lo diría, ¿eh? Parece que sí que conoces bastante bien el País Tropical. <br>¡Felicidades!', ' points! <br>I\'m freaking out, man! <br>Who would have thought it, huh? Looks like you know the Tropical Country pretty well.']

const TEN_POINTS_ONE = ['¡Qué ilusión! <br>¡Has acertado todas! <br>¡', 'Amazing! You got them all right!<br>'];

const TEN_POINTS_TWO = [' puntos! <br>Sube la música y pide una caipirinha. ¡Te la mereces!', ' points! <br>Turn up the music and order a caipirinha. You deserve it! <br><Congratulations!'];

const NEXT_QUESTION = ['¡Siguiente!', 'Next!'];

const END_GAME = ['¡Fin del partido!', 'Game Over!'];

const TITLE = ['¡Bienvenido al País Tropical!', 'Welcome to Brasil!'];

const TX_SAMBA = ['Brasil es mucho más que samba y fútbol.', 'Brazil is much more than samba and football.']

const FIND_OUT = ['Juega a <span>Patropi</span> y descubre!', 'Play <span>Patropi </span> and find out!'];

const HOW_TO_PLAY = ['Como jugar:', 'How to play:'];

const RULES_0NE = ['Activa el sonido de tu dispositivo.', 'Turn on the sound.'];

const RULES_TWO = ['En cada ronda, una foto.', 'On every round, a picture.'];

const RULES_THREE = ['Marca en el mapa donde ha sido sacada la fotografía. Sin googlear, ¡listillo!.', 'Mark on the map where the picture was taken. Do not use Google, smarty-pants!'];

const RULES_FOUR = ['Por cada acierto, 1 punto.', 'For every match, 1 point.'];

const RULES_FIVE = ['¡Tienes 10 oportunidades para probar que sabes todo sobre Brasil!', 'You have 10 opportunities to prove you know everything about Brazil!'];

const ROUNDS = ['Rondas: <span> 1 </span>', 'Rounds: <span> 1 </span>']

const POINTS = ['Puntos: <span> 1 </span>', 'Points: <span> 1 </span>']

